# Build Configuration for Allow2 Home Assistant Add-on
# Multi-architecture build definitions

build_from:
  amd64: ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.19
  i386: ghcr.io/home-assistant/i386-base-python:3.12-alpine3.19
  armhf: ghcr.io/home-assistant/armhf-base-python:3.12-alpine3.19
  armv7: ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.19
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.19

# Build arguments
args:
  BUILD_VERSION: "1.0.0"
  BUILD_DATE: ""
  BUILD_REF: ""
  BUILD_REPOSITORY: "https://github.com/Allow2/allow2homeassistant"
  BUILD_DESCRIPTION: "Allow2 Parental Controls Integration for Home Assistant"

# Labels to apply to the built image
labels:
  org.opencontainers.image.title: "Allow2 for Home Assistant"
  org.opencontainers.image.description: "Parental controls integration with Allow2 service"
  org.opencontainers.image.vendor: "Allow2"
  org.opencontainers.image.authors: "Allow2 <support@allow2.com>"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.url: "https://github.com/Allow2/allow2homeassistant"
  org.opencontainers.image.source: "https://github.com/Allow2/allow2homeassistant"
  org.opencontainers.image.documentation: "https://github.com/Allow2/allow2homeassistant/blob/main/README.md"
  io.hass.name: "Allow2"
  io.hass.description: "Parental controls integration with Allow2"
  io.hass.arch: "${BUILD_ARCH}"
  io.hass.type: "addon"
  io.hass.version: "${BUILD_VERSION}"

# Squash layers for smaller image
squash: false

# Cache settings
cache_tag: "cache"
